### ISSUE TITLE
[Bug]: Can't create notifications targeting a list of external ids

### ISSUE THREAD

**Issue by remiremi** [OneSignal/onesignal-node-api#66] opened 2023-08-15 15:31 UTC
### What happened?

The REST API makes it possible to send notifications to a list of users given their external ids: https://documentation.onesignal.com/reference/create-notification#platform-to-deliver-to

However the sdk doesn't seem to make it possible, because the field `include_aliases` expects an object of type `PlayerNotificationTargetIncludeAliases`, which definition doesn't make it possible to define the `external_id` field.

This is what the serialized JSON for `include_aliases` _should_ look like according to REST API documentation

```
  "include_aliases": {
    "external_id": ["external_user_id_on_push_email_sms"]
  },
```

### Steps to reproduce?

Install latest version of sdk.

To try and make the call with the SDK, run:

```
    const notification = new OneSignal.Notification()
    notification.app_id = this.appId
    notification.include_aliases = new OneSignal.PlayerNotificationTargetIncludeAliases();
    notification.include_aliases.external_id = ["my-id-1", "my-id-2"]
```

Typescript will complain that

```
"Property 'external_id' does not exist on type 'PlayerNotificationTargetIncludeAliases'.ts(2339)"
```

### What did you expect to happen?

I expect the SDK to have the correct type definition of `PlayerNotificationTargetIncludeAliases` so that the API call can be made with the correct parameters.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexrabin** [comment] 2023-08-17 04:05
I'm getting this error as well. The typescript types must be wrong

**Comment by iAmWillShepherd** [comment] 2023-08-31 16:25
@remiremi @alexrabin could you share which version of the SDK you're using?

**Comment by alexrabin** [comment] 2023-08-31 16:32
> @remiremi @alexrabin could you share which version of the SDK you're using?

I am using 2.0.1-beta2

**Comment by iAmWillShepherd** [comment] 2023-08-31 16:39
@remiremi 

> I am using 2.0.1-beta2

I suspected that, but I just wanted to confirm. Thanks for the prompt reply 🙏🏽

**Comment by alexrabin** [comment] 2023-08-31 16:47
@iAmWillShepherd thanks for looking into this!

**Comment by iAmWillShepherd** [comment] 2023-08-31 19:47
I've been able to reproduce this issue, and the team is aware of the problem. However, I have little insight into when a fix will be available.

 @remiremi 

` notification.include_aliases.external_id = ["my-id-1", "my-id-2"]`

You're 100 percent correct that this isn't possible. The only property you can access is `alias_label`.

Did you try including **EIDs** via the `Notification.include_external_user_ids` property?
 
```ts
const notification = new OneSignal.Notification()
notification.include_external_user_ids = ['id1', 'id2', 'id3']
```

**Comment by alexrabin** [comment] 2023-08-31 19:52
> I reproduce this issue, and the team is aware of the problem. However, I have little insight into when a fix will be available.
> 
> 
> 
> ```bash
> 
> ╭─iamwill@kronos ~/code/@onesignalDevelopers/OneSignal-Node-Sample ‹main●› 
> 
> ╰─$ ./bin/dev notification create -A 202d4f61-1ca9-42df-9d36-bb17d8613abf --name "Include EUID test" -- "Did it work"
> 
> Sending push notification... done
> 
> {
> 
>   "id": "",
> 
>   "errors": {}
> 
> }
> 
> ```
> 
> 
> 
>  @remiremi 
> 
> 
> 
> ` notification.include_aliases.external_id = ["my-id-1", "my-id-2"]`
> 
> 
> 
> You're 100 percent correct that this isn't possible. The only property you can access is `alias_label`.
> 
> 
> 
> Did you try including **EIDs** via the `Notification.include_external_user_ids` property?
> 
>  
> 
> ```ts
> 
> const notification = new OneSignal.Notification()
> 
> notification.include_external_user_ids = ['id1', 'id2', 'id3']
> 
> ```
> 
> 
> 
> 
> 
> 

Yes I am however the documentation says the attribute is deprecated:

> DEPRECATED: Use include_aliases with target_channel instead.

https://documentation.onesignal.com/reference/create-notification#send-to-specific-devices

**Comment by iAmWillShepherd** [comment] 2023-08-31 20:34
> @iAmWillShepherd Yes I am however the documentation says the attribute is deprecated:
> 
> > DEPRECATED: Use include_aliases with target_channel instead.
> 
> https://documentation.onesignal.com/reference/create-notification#send-to-specific-devices

They are indeed being deprecated, however, they should still be available to use until we ship an updated SDK.

**Comment by alexrabin** [comment] 2023-08-31 20:40
@iAmWillShepherd Yes the attribute does currently work but I'd rather not use an attribute that is deprecated.

**Comment by iAmWillShepherd** [comment] 2023-08-31 20:46
> @iAmWillShepherd Yes the attribute does currently work but I'd rather not use an attribute that is deprecated.

I understand. However, the property is not deprecated yet. It's marked as **Deprecating**, so it's a warning that it will be deprecated in the future and subsequently not supported some time after the official deprecation takes place. 

If you're OK with waiting indefinitely, we will ship an SDK that enables you to avoid using the deprecated property. My suggestion was meant to unblock you today. A fix will likely not be released at any point this week.

**Comment by alexrabin** [comment] 2023-08-31 20:50
@iAmWillShepherd I understand. Thank you

**Comment by kpturner** [comment] 2023-08-31 22:41
I am stuck on the same problem, but I want to include the `onesignal_id` alias rather than `external_id`.
What is the work around for that please?

**Comment by jpignata** [comment] 2023-10-14 16:13
> > @iAmWillShepherd Yes I am however the documentation says the attribute is deprecated:
> > > DEPRECATED: Use include_aliases with target_channel instead.
> > 
> > 
> > https://documentation.onesignal.com/reference/create-notification#send-to-specific-devices
> 
> They are indeed being deprecated, however, they should still be available to use until we ship an updated SDK.

@iAmWillShepherd I'm finding this isn't the case. The `invalid_external_user_ids` has been removed from `errors` in the response and moved to warnings. The value also preprendings the list of IDs with a string now according to the docs (https://documentation.onesignal.com/reference/create-notification). This appears to have changed on 6/2. I'd like to move to `include_aliases` in order to get a list of invalid external user IDs again.

Additionally, `invalid_aliases` doesn't exist on `Notification200Errors`. What's the ETA for this being wired up properly?

Thanks!

**Comment by manueltwistag** [comment] 2023-10-16 14:38
This is still an issue, We've tried to do the migration today but faced the type issues described in the comments. Any ETA on this?

**Comment by emawby** [comment] 2023-10-19 16:12
This SDK is undergoing another overhaul with more clear types and method names. The development for it is in progress and active and this issue is a priority

**Comment by abeisleem** [comment] 2023-10-21 10:24
I see the development in progress and commenting to add more visibility as I too am blocked by this issue. Thanks!

**Comment by jpignata** [comment] 2023-11-13 16:30
Heya - any progress here to report? I'd like to resume being able to report on failed push notifications.

**Comment by jpignata** [comment] 2023-12-01 22:54
@emawby Sorry to be a pain. Do you have an expected release date, so I can fix the bug on my end that this change caused?

**Comment by padejar** [comment] 2023-12-27 06:06
Will it be released anytime soon?

**Comment by michalstruck** [comment] 2023-12-27 17:42
@iAmWillShepherd @emawby any update? The situation is very unclear

**Comment by kpturner** [comment] 2024-01-31 23:06
It's beyond belief that an issue that's 5 months old has had no progress.  I'm inclined to believe this repo isn't maintained, which is understandable for some open source projects but this is supposed to be OneSignal's official node SDK 🤷‍♀️

**Comment by jfishman1** [comment] 2024-02-06 21:42
These are still the most up-to-date comments of this post:

https://github.com/OneSignal/onesignal-node-api/issues/66#issuecomment-1701688862

https://github.com/OneSignal/onesignal-node-api/issues/66#issuecomment-1771307881

These backend SDKs are going to take more time so they can be implemented correctly.

For now, if you want to target External IDs, continue using the `Notification.include_external_user_ids` property.

**Comment by MatheusLima7** [comment] 2024-03-06 15:26
I received this generic error when I try to create a notification:

`CreateNotificationSuccessResponse {
id: '',
errors: Notification200Errors {}
}`

I read that it is necessary to create a segment. It is possible to insert an array of ids in segment and after creating a notification it is necessary to use the id of segment how reference, but my account is free and it is impossible to create segment in free account. If someone to found the solution, please, talk me.

**Comment by kpturner** [comment] 2024-03-06 16:05
I've never had to create a segment to send notifications. There is a default segment for everything anyway AFAIK

**Comment by MatheusLima7** [comment] 2024-03-06 17:36
> I've never had to create a segment to send notifications. There is a default segment for everything anyway AFAIK

I am trying a method of resolve the problem, because include_external_user_ids not works for me.

**Comment by EinfachHans** [comment] 2024-05-03 08:21
This should work with [5.0.0-alpha.1](https://github.com/OneSignal/onesignal-node-api/releases/tag/5.0.0-alpha-01) now. 

The important change is this:
https://github.com/OneSignal/onesignal-node-api/commit/86801beb8c074f1a9c7593e199a558e9a1506298#diff-2541f67df3dacc0f2f4754190bdf4b5ab7670412a7c8fb9d6994220a077106feR63-R66

But worth to mention about this new alpha version:

> Documentation on API changes is lacking and under progress.
The README is outdated for this release.

**Comment by nan-li** [comment] 2024-05-09 22:07
Hi everyone, thanks again for reporting and for your patience.

As @EinfachHans mentioned, we recently released an alpha version of our latest user model API: [Release 5.0.0-alpha-01](https://github.com/OneSignal/onesignal-node-api/releases/tag/5.0.0-alpha-01) that addresses this and other issues.

Please read the release description for how to get started, and we appreciate any early feedback on this release.

**Closed** 2024-10-25 17:18 UTC
Labels: bug
